/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/aames/ros_imu/src/tau_under/msg/tau_under_msg.msg
 *
 */


#ifndef TAU_UNDER_MESSAGE_TAU_UNDER_MSG_H
#define TAU_UNDER_MESSAGE_TAU_UNDER_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tau_under
{
template <class ContainerAllocator>
struct tau_under_msg_
{
  typedef tau_under_msg_<ContainerAllocator> Type;

  tau_under_msg_()
    : left_shank_earth(0.0)
    , left_thigh_shank(0.0)
    , left_hip_thigh(0.0)
    , right_shank_earth(0.0)
    , right_thigh_shank(0.0)
    , right_hip_thigh(0.0)
    , tau(0.0)
    , right_is_stance(false)  {
    }
  tau_under_msg_(const ContainerAllocator& _alloc)
    : left_shank_earth(0.0)
    , left_thigh_shank(0.0)
    , left_hip_thigh(0.0)
    , right_shank_earth(0.0)
    , right_thigh_shank(0.0)
    , right_hip_thigh(0.0)
    , tau(0.0)
    , right_is_stance(false)  {
    }



   typedef double _left_shank_earth_type;
  _left_shank_earth_type left_shank_earth;

   typedef double _left_thigh_shank_type;
  _left_thigh_shank_type left_thigh_shank;

   typedef double _left_hip_thigh_type;
  _left_hip_thigh_type left_hip_thigh;

   typedef double _right_shank_earth_type;
  _right_shank_earth_type right_shank_earth;

   typedef double _right_thigh_shank_type;
  _right_thigh_shank_type right_thigh_shank;

   typedef double _right_hip_thigh_type;
  _right_hip_thigh_type right_hip_thigh;

   typedef double _tau_type;
  _tau_type tau;

   typedef uint8_t _right_is_stance_type;
  _right_is_stance_type right_is_stance;




  typedef boost::shared_ptr< ::tau_under::tau_under_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tau_under::tau_under_msg_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct tau_under_msg_

typedef ::tau_under::tau_under_msg_<std::allocator<void> > tau_under_msg;

typedef boost::shared_ptr< ::tau_under::tau_under_msg > tau_under_msgPtr;
typedef boost::shared_ptr< ::tau_under::tau_under_msg const> tau_under_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tau_under::tau_under_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tau_under::tau_under_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tau_under

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'tau_under': ['/home/aames/ros_imu/src/tau_under/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tau_under::tau_under_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tau_under::tau_under_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tau_under::tau_under_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tau_under::tau_under_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tau_under::tau_under_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tau_under::tau_under_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tau_under::tau_under_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6be40ba2e8dfc4bfad571b61abbe7647";
  }

  static const char* value(const ::tau_under::tau_under_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6be40ba2e8dfc4bfULL;
  static const uint64_t static_value2 = 0xad571b61abbe7647ULL;
};

template<class ContainerAllocator>
struct DataType< ::tau_under::tau_under_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tau_under/tau_under_msg";
  }

  static const char* value(const ::tau_under::tau_under_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tau_under::tau_under_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 left_shank_earth\n\
float64 left_thigh_shank\n\
float64 left_hip_thigh\n\
float64 right_shank_earth\n\
float64 right_thigh_shank\n\
float64 right_hip_thigh\n\
float64 tau\n\
bool right_is_stance\n\
";
  }

  static const char* value(const ::tau_under::tau_under_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tau_under::tau_under_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_shank_earth);
      stream.next(m.left_thigh_shank);
      stream.next(m.left_hip_thigh);
      stream.next(m.right_shank_earth);
      stream.next(m.right_thigh_shank);
      stream.next(m.right_hip_thigh);
      stream.next(m.tau);
      stream.next(m.right_is_stance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct tau_under_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tau_under::tau_under_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tau_under::tau_under_msg_<ContainerAllocator>& v)
  {
    s << indent << "left_shank_earth: ";
    Printer<double>::stream(s, indent + "  ", v.left_shank_earth);
    s << indent << "left_thigh_shank: ";
    Printer<double>::stream(s, indent + "  ", v.left_thigh_shank);
    s << indent << "left_hip_thigh: ";
    Printer<double>::stream(s, indent + "  ", v.left_hip_thigh);
    s << indent << "right_shank_earth: ";
    Printer<double>::stream(s, indent + "  ", v.right_shank_earth);
    s << indent << "right_thigh_shank: ";
    Printer<double>::stream(s, indent + "  ", v.right_thigh_shank);
    s << indent << "right_hip_thigh: ";
    Printer<double>::stream(s, indent + "  ", v.right_hip_thigh);
    s << indent << "tau: ";
    Printer<double>::stream(s, indent + "  ", v.tau);
    s << indent << "right_is_stance: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_is_stance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAU_UNDER_MESSAGE_TAU_UNDER_MSG_H
