imu:
  N: 1
  P: 
  - [1,2,3,4]
  - [5,6,7,8]
  Q: 
  - [1,2,3,4]
  - [5,6,7,8]
  R: 
  - [1,2,3,4]
  - [5,6,7,8]
  "0": 
    x_init: [1,2,3,4]
    r: [1,2,3,4]
  "1": 
    x_init: [1,2,3,4]
    r: [1,2,3,4]