/**
 * @brief AUTOGENERATED expressions from Mathematica
 */
#ifndef @EXPR_INCLUDE_GUARD@
	#define @EXPR_INCLUDE_GUARD@

#include <Eigen/Dense>

namespace @EXPR_NAMESPACE@ {

@EXPR_DECLARATIONS@

} // namespace @EXPR_NAMESPACE@

#endif // @EXPR_INCLUDE_GUARD@
