/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/aames/ros_imu/src/leg_pose/msg/legPose.msg
 *
 */


#ifndef LEG_POSE_MESSAGE_LEGPOSE_H
#define LEG_POSE_MESSAGE_LEGPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace leg_pose
{
template <class ContainerAllocator>
struct legPose_
{
  typedef legPose_<ContainerAllocator> Type;

  legPose_()
    : shank_earth(0.0)
    , thigh_shank(0.0)  {
    }
  legPose_(const ContainerAllocator& _alloc)
    : shank_earth(0.0)
    , thigh_shank(0.0)  {
    }



   typedef double _shank_earth_type;
  _shank_earth_type shank_earth;

   typedef double _thigh_shank_type;
  _thigh_shank_type thigh_shank;




  typedef boost::shared_ptr< ::leg_pose::legPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::leg_pose::legPose_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct legPose_

typedef ::leg_pose::legPose_<std::allocator<void> > legPose;

typedef boost::shared_ptr< ::leg_pose::legPose > legPosePtr;
typedef boost::shared_ptr< ::leg_pose::legPose const> legPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::leg_pose::legPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::leg_pose::legPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace leg_pose

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'leg_pose': ['/home/aames/ros_imu/src/leg_pose/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::leg_pose::legPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::leg_pose::legPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::leg_pose::legPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::leg_pose::legPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::leg_pose::legPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::leg_pose::legPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::leg_pose::legPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b95053568fdd0e718d845449ba7102d0";
  }

  static const char* value(const ::leg_pose::legPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb95053568fdd0e71ULL;
  static const uint64_t static_value2 = 0x8d845449ba7102d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::leg_pose::legPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "leg_pose/legPose";
  }

  static const char* value(const ::leg_pose::legPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::leg_pose::legPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 shank_earth\n\
float64 thigh_shank\n\
";
  }

  static const char* value(const ::leg_pose::legPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::leg_pose::legPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.shank_earth);
      stream.next(m.thigh_shank);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct legPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::leg_pose::legPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::leg_pose::legPose_<ContainerAllocator>& v)
  {
    s << indent << "shank_earth: ";
    Printer<double>::stream(s, indent + "  ", v.shank_earth);
    s << indent << "thigh_shank: ";
    Printer<double>::stream(s, indent + "  ", v.thigh_shank);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEG_POSE_MESSAGE_LEGPOSE_H
